/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Logs: typeof import('./components/Logs.vue')['default']
    OButton: typeof import('onu-ui')['OButton']
    Window: typeof import('./components/Window.vue')['default']
  }
}
